version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./tmp/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - localprom
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100

  blackbox-exporter:
    image: prom/blackbox-exporter
    networks:
      - localprom
    ports:
      - 9115:9115

  grafana:
    image: grafana/grafana
    volumes:
      - ./tmp/grafana/data:/var/lib/grafana
      - ./tmp/grafana/config:/etc/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - localprom
    ports:
      - 3000:3000

networks:
  localprom:
    driver: bridge
