version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./tmp/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets:/etc/prometheus/targets
    networks:
      - localprom
    ports:
      - 9090:9090

  blackbox-exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    networks:
      - localprom
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox/blackbox.yml

  grafana:
    image: grafana/grafana
    volumes:
      - ./tmp/grafana/data:/var/lib/grafana
      - ./tmp/grafana/config:/etc/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - localprom
    ports:
      - 3000:3000

  failed-api:
    image: failed-api
    networks:
      - localprom
    ports:
      - 8089:8089

networks:
  localprom:
    driver: bridge
