global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # To get metrics about the exporter itself
  - job_name: blackbox
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9115

  # To get metrics about the exporter’s targets
  - job_name: blackbox-http
    metrics_path: /probe
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.JSON
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115
